version: '3.7'

volumes:
  postgres:

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
        - POSTGRES_PASSWORD:'postgres'
    volumes:
        - postgres:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s webrick -p 80 -b '0.0.0.0'"
    volumes:
      - "./:/var/www"
    environment:
      # Resolve problem after linux upgrade to Buster (dh_key_too_small)
      - DATABASE_HOST=db
    ports:
        - "80:80"
    depends_on:
        - db
    dns:
      - 8.8.8.8
      - 4.4.4.4
